version: "3"
services:

  server:
    container_name: flask
    build: .
    ports: ['5000:5000']
    volumes: ['.:/usr/src/app']
    restart: always
    environment:
      ENV: DEVELOPMENT
      PROJECT_NAME: wspc-sandbox-app-wsky
     